name: API tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Clone test server repository
        run: git clone https://github.com/Nikita-Filonov/qa-automation-engineer-api-course.git

      - name: Install test server dependencies
        run: pip install -r qa-automation-engineer-api-course/requirements.txt

      - name: Start a test server
        env:
          APP_HOST: "http://localhost:8000"
          DATABASE_URL: "sqlite+aiosqlite:///./local.db"
          JWT_ALGORITHM: "HS256"
          JWT_SECRET_KEY: "qa-automation-engineer-api-course-secret-key"
          JWT_ACCESS_TOKEN_EXPIRE: 1800
          JWT_REFRESH_TOKEN_EXPIRE: 5184000
        run: uvicorn main:app --host 0.0.0.0 --port 8000 --app-dir ./qa-automation-engineer-api-course &

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install -r requirements.txt  

      - name: Run API tests with pytest and generate Allure results
        run: |
          pytest -m regression --alluredir=allure-results -n=2

      - name: Save allure-results as artifact
        uses: actions/upload-artifact@v4
        with:
          path: allure-results

  publish-report:
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Get Allure history
        uses: actions/checkout@v5
        with:
          ref: gh-pages
          path: gh-pages

      - name: Download allure-results
        uses: actions/download-artifact@v5
        with:
          path: allure-results

      - name: Generates Allure Report with history
        uses: simple-elf/allure-report-action@v1.13
        with:
          allure_results: allure-results
          allure_history: allure-history

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history